# Generated by Django 4.0.6 on 2023-05-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('product_name', models.CharField(max_length=200)),
                ('delivery_month', models.DateField()),
                ('futures_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='USTreasuryYields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('yield_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='calculator.marketdata')),
                ('underlying_future', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlying', to='calculator.marketdata')),
            ],
        ),
    ]
