# Generated by Django 4.0.6 on 2023-05-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_deliverymonth_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='delivery_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='calculator.deliverymonth'),
        ),
        migrations.AlterField(
            model_name='option',
            name='underlying_future',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlying', to='calculator.productname'),
        ),
    ]
